M48
; DRILL file KiCad 10.0.4 date 2026-09-26T11:42:47
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-26T11:42:47-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C3.400
%
G90
G05
T1
X170.94Y-148.5
X176.72Y-148.5
T2
X168.1Y-133.1
X178.57Y-108.2
T3
X167.82Y-128.9
X167.85Y-112.4
X178.82Y-128.9
X178.85Y-112.4
T4
X173.32Y-128.9
X173.35Y-112.4
M30
